[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
include = '(\.pyi?|\.ipynb)$'

[tool.isort]
profile = "black"
multi_line_output = 3
