import datetime
from textwrap import dedent

import numpy as np
import pytest
import xarray as xr

from ewatercycle.observation.usgs import _xml_to_xarray


@pytest.fixture()
def waterml_data():
    """This was generated by running

    ```python
    from ewatercycle.observation.usgs import _download_usgs_data
    print(_download_usgs_data("03109500", "2000-01-06T00:00:00", "2000-01-07T00:00:00"))
    ```
    """
    return dedent(
        """\
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <ns1:timeSeriesResponse
                xsi:schemaLocation="http://www.cuahsi.org/waterML/1.1/ http://waterservices.usgs.gov/WaterML-1.1.xsd"
                xmlns:ns1="http://www.cuahsi.org/waterML/1.1/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <ns1:queryInfo xmlns:ns2="http://www.cuahsi.org/waterML/1.1/">
                    <ns2:queryURL>
                        http://nwis.waterservices.usgs.gov/nwis/iv/startDT=2000-01-06T00%3A00&amp;endDT=2000-01-07T00%3A00&amp;parameterCd=00060&amp;sites=03109500&amp;format=waterml%2C1.1</ns2:queryURL>
                    <ns2:criteria>
                        <ns2:locationParam>[ALL:03109500]</ns2:locationParam>
                        <ns2:variableParam>[00060]</ns2:variableParam>
                        <ns2:timeParam>
                            <ns2:beginDateTime>2000-01-06T00:00:00.000</ns2:beginDateTime>
                            <ns2:endDateTime>2000-01-07T00:00:00.000</ns2:endDateTime>
                        </ns2:timeParam>
                    </ns2:criteria>
                    <ns2:note title="filter:sites">[ALL:03109500]</ns2:note>
                    <ns2:note title="filter:timeRange">[mode=RANGE, modifiedSince=null]
                        interval={INTERVAL[2000-01-06T00:00:00.000Z/2000-01-07T00:00:00.000Z]}</ns2:note>
                    <ns2:note title="filter:methodId">methodIds=[ALL]</ns2:note>
                    <ns2:note title="requestDT">2024-07-05T08:06:53.782Z</ns2:note>
                    <ns2:note title="requestId">8a673850-3aa5-11ef-9e48-4cd98f8df011</ns2:note>
                    <ns2:note title="disclaimer">Provisional data are subject to revision. Go to
                        http://waterdata.usgs.gov/nwis/help/?provisional for more information.</ns2:note>
                    <ns2:note title="server">nadww01</ns2:note>
                </ns1:queryInfo>
                <ns1:timeSeries name="USGS:03109500:00060:00000" xmlns:ns1="http://www.cuahsi.org/waterML/1.1/">
                    <ns1:sourceInfo xsi:type="ns1:SiteInfoType"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                        <ns1:siteName>Little Beaver Creek near East Liverpool OH</ns1:siteName>
                        <ns1:siteCode network="NWIS" agencyCode="USGS">03109500</ns1:siteCode>
                        <ns1:timeZoneInfo siteUsesDaylightSavingsTime="true">
                            <ns1:defaultTimeZone zoneOffset="-05:00" zoneAbbreviation="EST" />
                            <ns1:daylightSavingsTimeZone zoneOffset="-04:00" zoneAbbreviation="EDT" />
                        </ns1:timeZoneInfo>
                        <ns1:geoLocation>
                            <ns1:geogLocation xsi:type="ns1:LatLonPointType" srs="EPSG:4326">
                                <ns1:latitude>40.6758974</ns1:latitude>
                                <ns1:longitude>-80.5406244</ns1:longitude>
                            </ns1:geogLocation>
                        </ns1:geoLocation>
                        <ns1:siteProperty name="siteTypeCd">ST</ns1:siteProperty>
                        <ns1:siteProperty name="hucCd">05030101</ns1:siteProperty>
                        <ns1:siteProperty name="stateCd">39</ns1:siteProperty>
                        <ns1:siteProperty name="countyCd">39029</ns1:siteProperty>
                    </ns1:sourceInfo>
                    <ns1:variable ns1:oid="45807197">
                        <ns1:variableCode network="NWIS" vocabulary="NWIS:UnitValues" default="true"
                            variableID="45807197">00060</ns1:variableCode>
                        <ns1:variableName>Streamflow, ft&amp;#179;/s</ns1:variableName>
                        <ns1:variableDescription>Discharge, cubic feet per second</ns1:variableDescription>
                        <ns1:valueType>Derived Value</ns1:valueType>
                        <ns1:unit>
                            <ns1:unitCode>ft3/s</ns1:unitCode>
                        </ns1:unit>
                        <ns1:options>
                            <ns1:option name="Statistic" optionCode="00000" />
                        </ns1:options>
                        <ns1:noDataValue>-999999.0</ns1:noDataValue>
                    </ns1:variable>
                    <ns1:values>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T00:00:00.000-05:00">1570</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T01:00:00.000-05:00">1510</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T02:00:00.000-05:00">1430</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T03:00:00.000-05:00">1370</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T04:00:00.000-05:00">1320</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T05:00:00.000-05:00">1260</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T06:00:00.000-05:00">1220</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T07:00:00.000-05:00">1180</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T08:00:00.000-05:00">1140</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T09:00:00.000-05:00">1110</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T10:00:00.000-05:00">1070</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T11:00:00.000-05:00">1040</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T12:00:00.000-05:00">1020</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T13:00:00.000-05:00">995</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T14:00:00.000-05:00">967</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T15:00:00.000-05:00">947</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T16:00:00.000-05:00">920</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T17:00:00.000-05:00">901</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T18:00:00.000-05:00">888</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T19:00:00.000-05:00">868</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T20:00:00.000-05:00">849</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T21:00:00.000-05:00">831</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T22:00:00.000-05:00">818</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-06T23:00:00.000-05:00">806</ns1:value>
                        <ns1:value qualifiers="A [91]" dateTime="2000-01-07T00:00:00.000-05:00">788</ns1:value>
                        <ns1:qualifier qualifierID="0" ns1:network="NWIS" ns1:vocabulary="uv_rmk_cd">
                            <ns1:qualifierCode>[91]</ns1:qualifierCode>
                            <ns1:qualifierDescription>Returned when there is no matching qualifier.</ns1:qualifierDescription>
                        </ns1:qualifier>
                        <ns1:qualifier qualifierID="1" ns1:network="NWIS" ns1:vocabulary="uv_rmk_cd">
                            <ns1:qualifierCode>A</ns1:qualifierCode>
                            <ns1:qualifierDescription>Approved for publication -- Processing and review
                                completed.</ns1:qualifierDescription>
                        </ns1:qualifier>
                        <ns1:method methodID="110067">
                            <ns1:methodDescription></ns1:methodDescription>
                        </ns1:method>
                    </ns1:values>
                </ns1:timeSeries>
            </ns1:timeSeriesResponse>
    """
    )


def test_xml_to_xarray(waterml_data: str):
    result = _xml_to_xarray(waterml_data)
    expected = xr.Dataset.from_dict(
        {
            "coords": {
                "time": {
                    "dims": ("time",),
                    "attrs": {},
                    "data": [
                        datetime.datetime(2000, 1, 6, 5, 0),
                        datetime.datetime(2000, 1, 6, 6, 0),
                        datetime.datetime(2000, 1, 6, 7, 0),
                        datetime.datetime(2000, 1, 6, 8, 0),
                        datetime.datetime(2000, 1, 6, 9, 0),
                        datetime.datetime(2000, 1, 6, 10, 0),
                        datetime.datetime(2000, 1, 6, 11, 0),
                        datetime.datetime(2000, 1, 6, 12, 0),
                        datetime.datetime(2000, 1, 6, 13, 0),
                        datetime.datetime(2000, 1, 6, 14, 0),
                        datetime.datetime(2000, 1, 6, 15, 0),
                        datetime.datetime(2000, 1, 6, 16, 0),
                        datetime.datetime(2000, 1, 6, 17, 0),
                        datetime.datetime(2000, 1, 6, 18, 0),
                        datetime.datetime(2000, 1, 6, 19, 0),
                        datetime.datetime(2000, 1, 6, 20, 0),
                        datetime.datetime(2000, 1, 6, 21, 0),
                        datetime.datetime(2000, 1, 6, 22, 0),
                        datetime.datetime(2000, 1, 6, 23, 0),
                        datetime.datetime(2000, 1, 7, 0, 0),
                        datetime.datetime(2000, 1, 7, 1, 0),
                        datetime.datetime(2000, 1, 7, 2, 0),
                        datetime.datetime(2000, 1, 7, 3, 0),
                        datetime.datetime(2000, 1, 7, 4, 0),
                        datetime.datetime(2000, 1, 7, 5, 0),
                    ],
                }
            },
            "attrs": {
                "title": "USGS Data from streamflow data",
                "station": "Little Beaver Creek near East Liverpool OH",
                "stationid": "03109500",
                "location": (np.float64(40.6758974), np.float64(-80.5406244)),
            },
            "dims": {"time": 25},
            "data_vars": {
                "streamflow": {
                    "dims": ("time",),
                    "attrs": {"units": "m3/s"},
                    "data": [
                        44.45703125,
                        42.758033752441406,
                        40.49271011352539,
                        38.7937126159668,
                        37.37788391113281,
                        35.678890228271484,
                        34.546226501464844,
                        33.4135627746582,
                        32.28089904785156,
                        31.4314022064209,
                        30.29874038696289,
                        29.449241638183594,
                        28.882911682128906,
                        28.174997329711914,
                        27.382131576538086,
                        26.815799713134766,
                        26.051252365112305,
                        25.51323890686035,
                        25.145122528076172,
                        24.57879066467285,
                        24.040775299072266,
                        23.531078338623047,
                        23.162961959838867,
                        22.823162078857422,
                        22.313465118408203,
                    ],
                }
            },
        }
    )

    xr.testing.assert_identical(result, expected)
