name: Python package

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
      fail-fast: false
    name: Run tests in conda environment ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ewatercycle
          environment-file: environment.yml
          mamba-version: "*"
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip3 install -e .[dev]
      - name: Test with pytest
        run: pytest
        shell: bash -l {0}
