name: Python package

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
      fail-fast: false
    name: Run tests in conda environment ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-lock.yml
          environment-name: ci
          cache-environment: true
          init-shell: bash
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip3 install -e .[dev] build
      - name: Test with pytest
        run: pytest
        shell: bash -l {0}
      - name: Build
        run: python -m build
        shell: bash -l {0}
