name: Static code analysis 🔍️

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install ruff
      - name: Non-ruff lint
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: ruff,ruff-format
      - name: Ruff Lint
        run: ruff check --output-format=github .
      - name: Check format
        run: ruff format --check
